# Edit this file only as instructed.
---
# language: the choices are (uncomment exactly one)
#   java, swift, script or c#
language: java
#language: swift
#language: script
#language: c#
#language: c
#language: c++

# files: list your source file(s) and do not use tabs in this file.
#   Each file must be preceeded by a hyphen and indented two spaces.
#   It is safest to enclose the filename in "double quotes".
#
#   Do not include a leading "/".  The pathname must be relative to
#   the root folder of your repo.
files: 
#  #- "TuringMachine/main.swift"  
    - "TuringMachine/src/TuringMachine.java"
#  #- "TuringMachine.c"
#  #- "TuringMachine.cpp"
